/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'workType' : string,
  'driverId' : bigint,
  'paymentMethod' : PaymentMethod,
  'hours' : bigint,
  'date' : bigint,
  'tractorId' : bigint,
  'ratePerHour' : bigint,
  'totalAmount' : bigint,
  'notes' : string,
  'advancePaid' : bigint,
  'partyId' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Driver {
  'id' : bigint,
  'assignedTractorId' : [] | [bigint],
  'name' : string,
  'performanceNotes' : string,
  'phone' : string,
}
export interface Expense {
  'id' : bigint,
  'driverId' : bigint,
  'date' : bigint,
  'tractorId' : bigint,
  'notes' : string,
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export type ExpenseCategory = { 'other' : null } |
  { 'driverPayment' : null } |
  { 'maintenance' : null } |
  { 'diesel' : null };
export interface Party {
  'id' : bigint,
  'name' : string,
  'creditBalance' : bigint,
  'address' : string,
  'phone' : string,
}
export interface Payment {
  'id' : bigint,
  'method' : PaymentMethod,
  'bookingId' : bigint,
  'date' : bigint,
  'notes' : string,
  'amount' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'cash' : null } |
  { 'split' : null };
export interface Tractor {
  'id' : bigint,
  'status' : TractorStatus,
  'driverId' : [] | [bigint],
  'model' : string,
  'name' : string,
  'ratePerHour' : bigint,
}
export type TractorStatus = { 'busy' : null } |
  { 'free' : null };
export interface UserProfile {
  'ownerName' : string,
  'businessName' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriverToTractor' : ActorMethod<[bigint, [] | [bigint]], undefined>,
  'createBooking' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      PaymentMethod,
      string,
    ],
    bigint
  >,
  'createDriver' : ActorMethod<[string, string, string], bigint>,
  'createExpense' : ActorMethod<
    [bigint, bigint, ExpenseCategory, bigint, bigint, string],
    bigint
  >,
  'createParty' : ActorMethod<[string, string, string], bigint>,
  'createPayment' : ActorMethod<
    [bigint, bigint, PaymentMethod, bigint, string],
    bigint
  >,
  'createTractor' : ActorMethod<[string, string, bigint], bigint>,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'deleteDriver' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteParty' : ActorMethod<[bigint], undefined>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'deleteTractor' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllDrivers' : ActorMethod<[], Array<Driver>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllParties' : ActorMethod<[], Array<Party>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllTractors' : ActorMethod<[], Array<Tractor>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingsByDateRange' : ActorMethod<[bigint, bigint], Array<Booking>>,
  'getBookingsByParty' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsByTractor' : ActorMethod<[bigint], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriver' : ActorMethod<[bigint], [] | [Driver]>,
  'getEarningsThisMonth' : ActorMethod<[], bigint>,
  'getEarningsToday' : ActorMethod<[], bigint>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getExpensesByDriver' : ActorMethod<[bigint], bigint>,
  'getExpensesByTractor' : ActorMethod<[bigint], bigint>,
  'getNetProfit' : ActorMethod<[bigint, bigint], bigint>,
  'getPartiesWithPendingCredit' : ActorMethod<[], Array<Party>>,
  'getParty' : ActorMethod<[bigint], [] | [Party]>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getTotalEarnings' : ActorMethod<[], bigint>,
  'getTractor' : ActorMethod<[bigint], [] | [Tractor]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBooking' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      PaymentMethod,
      BookingStatus,
      string,
    ],
    undefined
  >,
  'updateDriver' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateExpense' : ActorMethod<
    [bigint, bigint, bigint, ExpenseCategory, bigint, bigint, string],
    undefined
  >,
  'updateParty' : ActorMethod<[bigint, string, string, string], undefined>,
  'updatePayment' : ActorMethod<
    [bigint, bigint, bigint, PaymentMethod, bigint, string],
    undefined
  >,
  'updateTractor' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateTractorStatus' : ActorMethod<[bigint, TractorStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];