/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
  'split' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'maintenance' : IDL.Null,
  'diesel' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'workType' : IDL.Text,
  'driverId' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'hours' : IDL.Nat,
  'date' : IDL.Int,
  'tractorId' : IDL.Nat,
  'ratePerHour' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Text,
  'advancePaid' : IDL.Nat,
  'partyId' : IDL.Nat,
});
export const Driver = IDL.Record({
  'id' : IDL.Nat,
  'assignedTractorId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'performanceNotes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'tractorId' : IDL.Nat,
  'notes' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Nat,
});
export const Party = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'creditBalance' : IDL.Int,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'method' : PaymentMethod,
  'bookingId' : IDL.Nat,
  'date' : IDL.Int,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const TractorStatus = IDL.Variant({
  'busy' : IDL.Null,
  'free' : IDL.Null,
});
export const Tractor = IDL.Record({
  'id' : IDL.Nat,
  'status' : TractorStatus,
  'driverId' : IDL.Opt(IDL.Nat),
  'model' : IDL.Text,
  'name' : IDL.Text,
  'ratePerHour' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'ownerName' : IDL.Text,
  'businessName' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriverToTractor' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        PaymentMethod,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createDriver' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createExpense' : IDL.Func(
      [IDL.Nat, ExpenseCategory, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createParty' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, PaymentMethod, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTractor' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteDriver' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteParty' : IDL.Func([IDL.Nat], [], []),
  'deletePayment' : IDL.Func([IDL.Nat], [], []),
  'deleteTractor' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllTractors' : IDL.Func([], [IDL.Vec(Tractor)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByParty' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getBookingsByTractor' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriver' : IDL.Func([IDL.Nat], [IDL.Opt(Driver)], ['query']),
  'getEarningsThisMonth' : IDL.Func([], [IDL.Nat], ['query']),
  'getEarningsToday' : IDL.Func([], [IDL.Nat], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getExpensesByTractor' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getNetProfit' : IDL.Func([IDL.Int, IDL.Int], [IDL.Int], ['query']),
  'getPartiesWithPendingCredit' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'getParty' : IDL.Func([IDL.Nat], [IDL.Opt(Party)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getTotalEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getTractor' : IDL.Func([IDL.Nat], [IDL.Opt(Tractor)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        PaymentMethod,
        BookingStatus,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateDriver' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Nat, ExpenseCategory, IDL.Nat, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateParty' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, PaymentMethod, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateTractor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateTractorStatus' : IDL.Func([IDL.Nat, TractorStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cash' : IDL.Null,
    'split' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'maintenance' : IDL.Null,
    'diesel' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'workType' : IDL.Text,
    'driverId' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'hours' : IDL.Nat,
    'date' : IDL.Int,
    'tractorId' : IDL.Nat,
    'ratePerHour' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Text,
    'advancePaid' : IDL.Nat,
    'partyId' : IDL.Nat,
  });
  const Driver = IDL.Record({
    'id' : IDL.Nat,
    'assignedTractorId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'performanceNotes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'tractorId' : IDL.Nat,
    'notes' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Nat,
  });
  const Party = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'creditBalance' : IDL.Int,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'method' : PaymentMethod,
    'bookingId' : IDL.Nat,
    'date' : IDL.Int,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const TractorStatus = IDL.Variant({ 'busy' : IDL.Null, 'free' : IDL.Null });
  const Tractor = IDL.Record({
    'id' : IDL.Nat,
    'status' : TractorStatus,
    'driverId' : IDL.Opt(IDL.Nat),
    'model' : IDL.Text,
    'name' : IDL.Text,
    'ratePerHour' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'ownerName' : IDL.Text,
    'businessName' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriverToTractor' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          PaymentMethod,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createDriver' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createExpense' : IDL.Func(
        [IDL.Nat, ExpenseCategory, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createParty' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentMethod, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTractor' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteDriver' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteParty' : IDL.Func([IDL.Nat], [], []),
    'deletePayment' : IDL.Func([IDL.Nat], [], []),
    'deleteTractor' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllTractors' : IDL.Func([], [IDL.Vec(Tractor)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByParty' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getBookingsByTractor' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriver' : IDL.Func([IDL.Nat], [IDL.Opt(Driver)], ['query']),
    'getEarningsThisMonth' : IDL.Func([], [IDL.Nat], ['query']),
    'getEarningsToday' : IDL.Func([], [IDL.Nat], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getExpensesByTractor' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getNetProfit' : IDL.Func([IDL.Int, IDL.Int], [IDL.Int], ['query']),
    'getPartiesWithPendingCredit' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'getParty' : IDL.Func([IDL.Nat], [IDL.Opt(Party)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getTotalEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getTractor' : IDL.Func([IDL.Nat], [IDL.Opt(Tractor)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          PaymentMethod,
          BookingStatus,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateDriver' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Nat, ExpenseCategory, IDL.Nat, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateParty' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, PaymentMethod, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateTractor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateTractorStatus' : IDL.Func([IDL.Nat, TractorStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };