/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tractor {
    id: bigint;
    status: TractorStatus;
    driverId?: bigint;
    model: string;
    name: string;
    ratePerHour: bigint;
}
export interface Party {
    id: bigint;
    name: string;
    creditBalance: bigint;
    address: string;
    phone: string;
}
export interface Driver {
    id: bigint;
    assignedTractorId?: bigint;
    name: string;
    performanceNotes: string;
    phone: string;
}
export interface Payment {
    id: bigint;
    method: PaymentMethod;
    bookingId: bigint;
    date: bigint;
    notes: string;
    amount: bigint;
}
export interface Expense {
    id: bigint;
    date: bigint;
    tractorId: bigint;
    notes: string;
    category: ExpenseCategory;
    amount: bigint;
}
export interface UserProfile {
    ownerName: string;
    businessName: string;
    address: string;
    phone: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    workType: string;
    driverId: bigint;
    paymentMethod: PaymentMethod;
    hours: bigint;
    date: bigint;
    tractorId: bigint;
    ratePerHour: bigint;
    totalAmount: bigint;
    notes: string;
    advancePaid: bigint;
    partyId: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export enum ExpenseCategory {
    other = "other",
    maintenance = "maintenance",
    diesel = "diesel"
}
export enum PaymentMethod {
    upi = "upi",
    cash = "cash",
    split = "split"
}
export enum TractorStatus {
    busy = "busy",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDriverToTractor(tractorId: bigint, driverId: bigint | null): Promise<void>;
    createBooking(tractorId: bigint, driverId: bigint, partyId: bigint, workType: string, date: bigint, hours: bigint, ratePerHour: bigint, advancePaid: bigint, paymentMethod: PaymentMethod, notes: string): Promise<bigint>;
    createDriver(name: string, phone: string, performanceNotes: string): Promise<bigint>;
    createExpense(tractorId: bigint, category: ExpenseCategory, amount: bigint, date: bigint, notes: string): Promise<bigint>;
    createParty(name: string, phone: string, address: string): Promise<bigint>;
    createPayment(bookingId: bigint, amount: bigint, method: PaymentMethod, date: bigint, notes: string): Promise<bigint>;
    createTractor(name: string, model: string, ratePerHour: bigint): Promise<bigint>;
    deleteBooking(id: bigint): Promise<void>;
    deleteDriver(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteParty(id: bigint): Promise<void>;
    deletePayment(id: bigint): Promise<void>;
    deleteTractor(id: bigint): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllDrivers(): Promise<Array<Driver>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllParties(): Promise<Array<Party>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllTractors(): Promise<Array<Tractor>>;
    getBooking(id: bigint): Promise<Booking | null>;
    getBookingsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Booking>>;
    getBookingsByParty(partyId: bigint): Promise<Array<Booking>>;
    getBookingsByTractor(tractorId: bigint): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDriver(id: bigint): Promise<Driver | null>;
    getEarningsThisMonth(): Promise<bigint>;
    getEarningsToday(): Promise<bigint>;
    getExpense(id: bigint): Promise<Expense | null>;
    getExpensesByTractor(tractorId: bigint): Promise<bigint>;
    getNetProfit(startDate: bigint, endDate: bigint): Promise<bigint>;
    getPartiesWithPendingCredit(): Promise<Array<Party>>;
    getParty(id: bigint): Promise<Party | null>;
    getPayment(id: bigint): Promise<Payment | null>;
    getTotalEarnings(): Promise<bigint>;
    getTractor(id: bigint): Promise<Tractor | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBooking(id: bigint, tractorId: bigint, driverId: bigint, partyId: bigint, workType: string, date: bigint, hours: bigint, ratePerHour: bigint, advancePaid: bigint, paymentMethod: PaymentMethod, status: BookingStatus, notes: string): Promise<void>;
    updateDriver(id: bigint, name: string, phone: string, performanceNotes: string): Promise<void>;
    updateExpense(id: bigint, tractorId: bigint, category: ExpenseCategory, amount: bigint, date: bigint, notes: string): Promise<void>;
    updateParty(id: bigint, name: string, phone: string, address: string): Promise<void>;
    updatePayment(id: bigint, bookingId: bigint, amount: bigint, method: PaymentMethod, date: bigint, notes: string): Promise<void>;
    updateTractor(id: bigint, name: string, model: string, ratePerHour: bigint): Promise<void>;
    updateTractorStatus(id: bigint, status: TractorStatus): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Driver as _Driver, Expense as _Expense, ExpenseCategory as _ExpenseCategory, Party as _Party, Payment as _Payment, PaymentMethod as _PaymentMethod, Tractor as _Tractor, TractorStatus as _TractorStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDriverToTractor(arg0: bigint, arg1: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDriverToTractor(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDriverToTractor(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: PaymentMethod, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
    async createDriver(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDriver(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDriver(arg0, arg1, arg2);
            return result;
        }
    }
    async createExpense(arg0: bigint, arg1: ExpenseCategory, arg2: bigint, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0, to_candid_ExpenseCategory_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0, to_candid_ExpenseCategory_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createParty(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createParty(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParty(arg0, arg1, arg2);
            return result;
        }
    }
    async createPayment(arg0: bigint, arg1: bigint, arg2: PaymentMethod, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createTractor(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTractor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTractor(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteDriver(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDriver(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteParty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParty(arg0);
            return result;
        }
    }
    async deletePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteTractor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTractor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTractor(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrivers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrivers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParties(): Promise<Array<Party>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParties();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTractors(): Promise<Array<Tractor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTractors();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTractors();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDateRange(arg0, arg1);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDateRange(arg0, arg1);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByParty(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByParty(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByParty(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByTractor(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByTractor(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByTractor(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriver(arg0: bigint): Promise<Driver | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEarningsThisMonth(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsThisMonth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsThisMonth();
            return result;
        }
    }
    async getEarningsToday(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsToday();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsToday();
            return result;
        }
    }
    async getExpense(arg0: bigint): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByTractor(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByTractor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByTractor(arg0);
            return result;
        }
    }
    async getNetProfit(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetProfit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetProfit(arg0, arg1);
            return result;
        }
    }
    async getPartiesWithPendingCredit(): Promise<Array<Party>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartiesWithPendingCredit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartiesWithPendingCredit();
            return result;
        }
    }
    async getParty(arg0: bigint): Promise<Party | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalEarnings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalEarnings();
            return result;
        }
    }
    async getTractor(arg0: bigint): Promise<Tractor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTractor(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTractor(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBooking(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: PaymentMethod, arg10: BookingStatus, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg9), to_candid_BookingStatus_n41(this._uploadFile, this._downloadFile, arg10), arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg9), to_candid_BookingStatus_n41(this._uploadFile, this._downloadFile, arg10), arg11);
            return result;
        }
    }
    async updateDriver(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: bigint, arg2: ExpenseCategory, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, to_candid_ExpenseCategory_n6(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, to_candid_ExpenseCategory_n6(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async updateParty(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePayment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: PaymentMethod, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1, arg2, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1, arg2, to_candid_PaymentMethod_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async updateTractor(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTractor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTractor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTractorStatus(arg0: bigint, arg1: TractorStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTractorStatus(arg0, to_candid_TractorStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTractorStatus(arg0, to_candid_TractorStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Driver_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Driver): Driver {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TractorStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TractorStatus): TractorStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Tractor_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tractor): Tractor {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Driver]): Driver | null {
    return value.length === 0 ? null : from_candid_Driver_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expense]): Expense | null {
    return value.length === 0 ? null : from_candid_Expense_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Party]): Party | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tractor]): Tractor | null {
    return value.length === 0 ? null : from_candid_Tractor_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    workType: string;
    driverId: bigint;
    paymentMethod: _PaymentMethod;
    hours: bigint;
    date: bigint;
    tractorId: bigint;
    ratePerHour: bigint;
    totalAmount: bigint;
    notes: string;
    advancePaid: bigint;
    partyId: bigint;
}): {
    id: bigint;
    status: BookingStatus;
    workType: string;
    driverId: bigint;
    paymentMethod: PaymentMethod;
    hours: bigint;
    date: bigint;
    tractorId: bigint;
    ratePerHour: bigint;
    totalAmount: bigint;
    notes: string;
    advancePaid: bigint;
    partyId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n11(_uploadFile, _downloadFile, value.status),
        workType: value.workType,
        driverId: value.driverId,
        paymentMethod: from_candid_PaymentMethod_n13(_uploadFile, _downloadFile, value.paymentMethod),
        hours: value.hours,
        date: value.date,
        tractorId: value.tractorId,
        ratePerHour: value.ratePerHour,
        totalAmount: value.totalAmount,
        notes: value.notes,
        advancePaid: value.advancePaid,
        partyId: value.partyId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignedTractorId: [] | [bigint];
    name: string;
    performanceNotes: string;
    phone: string;
}): {
    id: bigint;
    assignedTractorId?: bigint;
    name: string;
    performanceNotes: string;
    phone: string;
} {
    return {
        id: value.id,
        assignedTractorId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.assignedTractorId)),
        name: value.name,
        performanceNotes: value.performanceNotes,
        phone: value.phone
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: bigint;
    tractorId: bigint;
    notes: string;
    category: _ExpenseCategory;
    amount: bigint;
}): {
    id: bigint;
    date: bigint;
    tractorId: bigint;
    notes: string;
    category: ExpenseCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        tractorId: value.tractorId,
        notes: value.notes,
        category: from_candid_ExpenseCategory_n22(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    method: _PaymentMethod;
    bookingId: bigint;
    date: bigint;
    notes: string;
    amount: bigint;
}): {
    id: bigint;
    method: PaymentMethod;
    bookingId: bigint;
    date: bigint;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n13(_uploadFile, _downloadFile, value.method),
        bookingId: value.bookingId,
        date: value.date,
        notes: value.notes,
        amount: value.amount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TractorStatus;
    driverId: [] | [bigint];
    model: string;
    name: string;
    ratePerHour: bigint;
}): {
    id: bigint;
    status: TractorStatus;
    driverId?: bigint;
    model: string;
    name: string;
    ratePerHour: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TractorStatus_n30(_uploadFile, _downloadFile, value.status),
        driverId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.driverId)),
        model: value.model,
        name: value.name,
        ratePerHour: value.ratePerHour
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
} | {
    split: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cash" in value ? PaymentMethod.cash : "split" in value ? PaymentMethod.split : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    maintenance: null;
} | {
    diesel: null;
}): ExpenseCategory {
    return "other" in value ? ExpenseCategory.other : "maintenance" in value ? ExpenseCategory.maintenance : "diesel" in value ? ExpenseCategory.diesel : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    busy: null;
} | {
    free: null;
}): TractorStatus {
    return "busy" in value ? TractorStatus.busy : "free" in value ? TractorStatus.free : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Driver>): Array<Driver> {
    return value.map((x)=>from_candid_Driver_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tractor>): Array<Tractor> {
    return value.map((x)=>from_candid_Tractor_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_TractorStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TractorStatus): _TractorStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TractorStatus): {
    busy: null;
} | {
    free: null;
} {
    return value == TractorStatus.busy ? {
        busy: null
    } : value == TractorStatus.free ? {
        free: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cash: null;
} | {
    split: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.split ? {
        split: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    other: null;
} | {
    maintenance: null;
} | {
    diesel: null;
} {
    return value == ExpenseCategory.other ? {
        other: null
    } : value == ExpenseCategory.maintenance ? {
        maintenance: null
    } : value == ExpenseCategory.diesel ? {
        diesel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
